
---

### `.github/workflows/tweet.yml`
```yaml
name: post-notes

on:
  schedule:
    - cron: "*/102 * * * *"   # every 102 minutes, 14 tweets/day, doesn't exceed free rate limit
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tweeter
        env:
          API_KEY: wMQCbqhaMTH4lU6qiO1YLRmCE
          API_SECRET: QkCY15nGqCbVtCIHFmnXFxxlGru6FIsFULPL1dcWA0LpyAGhSo
          ACCESS_TOKEN: 1429986062869401603-86Ob603OxqlJQSOhmBytzmBUIvnLv1
          ACCESS_TOKEN_SECRET: ssNeqt45cyhsfxPW6wWxv7kapexo7GB5C6X9oSbHNg6sk
          PAUSE_SEC: 2
          MAX_PER_RUN: 1
        run: python tweeter.py
